# -*- coding: utf-8 -*-
"""exploration_cosines.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckA3vMh4A1XVC9g1HtrHofNwkK12Na5f
"""

import numpy as np
import matplotlib.pyplot as plt



mat = np.array([np.random.normal(0, 1, size=10), np.random.normal(0, 1, size=10)]).transpose()
mat

plt.scatter(mat[:,0], mat[:,1])

query = np.array([0, 0])
plt.scatter(mat[:,0], mat[:,1])
plt.scatter(query[0], query[1], color="red")

diffs = mat - query
plt.scatter(diffs[:,0], diffs[:,1])
plt.scatter(0, 0, color="red")

import pandas as pd

def cosine(v1, v2):
  return v1.dot(v2) / np.linalg.norm(v1) / np.linalg.norm(v2)

result = np.zeros([diffs.shape[0], diffs.shape[0]])

for row1 in range(diffs.shape[0]):
  for row2 in range(diffs.shape[0]):
    result[row1, row2] = cosine(diffs[row1,:], diffs[row2,:])

print(pd.DataFrame(result))

iu = np.triu_indices(diffs.shape[0], k=1)
allCosines = result[iu]
np.mean(allCosines), np.std(allCosines)

